- accordion:
  letter: a
  data:
    - title: How do I apply for a licence?
      content: |
        Step 1: Search for the licence you want.

        Step 2: Add the licence as a Task.

        Step 3: Fill in the information required.

        Step 4: Declare information to be accurate and submit.

        Step 5: Make payment.

        You will find your application under In Progress on your GoBusiness Dashboard.

    - title: How do I withdraw an application?
      content: |
        Step 1: Click on the 'Processing' section on your GoBusiness Dashboard.

        Step 2: Search for the application you want to withdraw.

        Step 3: Click on the '...' button and select Withdraw.

    - title: How do I amend an existing licence?
      content: |
        To amend licences on GoBusiness:

        Step 1: Click on the Active section under My Licences.

        Step 2: Search for the licence you want to amend.

        Step 3: Click on the '...' button and select Amend.

        Step 4: Amend the details you want, declare the information to be accurate and make payment (if any).

        You will then be able to see your amended application under the In Progress section of your GoBusiness Dashboard. Once the amendment is approved, you will find your licence in the Active Licences section. Please note that amendments may only be made for some licences.

        For licences that are still on LicenceOne, please log in to LicenceOne and amend it there.

    - title: How do I renew an existing licence?
      content: |
        To renew licences on GoBusiness:

        Step 1: Click on the Due For Renewal section under My Licences.

        Step 2: Search for the licence you want to renew.

        Step 3: Click on the ... button and select Renew.

        Step 4: Ensure and declare the information to be accurate and make payment (if any).

        You will then be able to see your renewal application under the In Progress section of your GoBusiness Dashboard. Once the renewal is approved, you will find your licence in the Active Licences section.

        For licences that are still on LicenceOne, please log in to LicenceOne and amend it there.

    - title: How do I cancel an existing licence?
      content: |
        To cancel licences on GoBusiness:

        Step 1: Click on My Licences.

        Step 2: Search for the licence you want to cancel.

        Step 3: Click on the ... button and select Cancel.

        You will then be able to see your application for cancellation under the In Progress section of your GoBusiness Dashboard. Once the cancellation is approved, you will no longer see the licence in the Active Licences section. Please note that not all licences can be cancelled.

        For licences that are still on LicenceOne, please log in to LicenceOne and amend it there.

- accordion:
  letter: b
  data:
    - title: Which licences and permits can I apply for here?
      content: |
        You can refer to this full list of [licences and permits](/licences/find-licence-by-agency/?src=licences_faq) available on GoBusiness, or add them directly on [GoBusiness Dashboard](https://dashboard.gobusiness.gov.sg/addtask??src=licences_faq){:target="_blank"}{:rel="noopener"}.

    - title: What is an Application Journey?
      content: |
        An Application Journey shows the correct order to apply for your licences in order to start running your business. It is customized based on your business concept.

    - title: Why can't I apply for some of the licences in my Application Journey?
      content: |
        Some licences are required before you can apply for others. Based on this sequence, the Application Journey shows you the correct order in which to apply for them and tells you which licences you will need before applying for the next one.

        Licences indicated in grey require you to obtain another licence first before you can proceed.

    - title: What does 'licence dependency' mean?
      content: |
        Some licences are required before you can apply for others. Based on this, the Guided Journey feature maps out the correct order to apply for them and shows you which licences you will need before applying for the next one.

        For example:

        SFA's Food Shop Licence and SPF's Public Entertainment Licence and Liquor Licence are dependent on landowner's permission (i.e. URA, HDB, Private, SLA, JTC etc)

        Halal Certification is dependent on Food Shop Licence approval.

    - title: Why are some licences incompatible?
      content: |
        Some licences are mutually exclusive and cannot be applied for together. Here is a list of incompatible licences:

        Halal Certification is mutually exclusive to Liquor Licence and Tobacco Licence.
        The Liquor Licence and Public Entertainment Licence may not be compatible with certain food shop types (e.g. Canteen)

    - title: What is a Food Shop type?
      content: |
        The Singapore Food Agency (SFA) classifies food & beverage businesses according to their business concept.

        Here is a [list of all Food Shop types](https://go.gov.sg/food-shop-types/?src=licences_faq){:target="_blank"}.

    - title: How do I know which Food Shop type my business falls under?
      content: |
        Here is a [list of all Food Shop types](/images/grow/FoodShopTypeMapping.pdf?src=licences_faq){:target="_blank"} and their descriptions.

        If you are not sure, simply use our Guided Journey feature and answer a series of questions about your business to find out which Food Shop type it falls under.

    - title: What falls under 'Others' in Food Shop Type?
      content: |
        Out of the Food Shop types recommended for you, you are advised to select the option that best describes your business concept. If none of the options apply, you may select 'Others'.

    - title: Why can't I select more than one Food Shop type?
      content: |
        Each business location is only allowed to have one Food Shop type.

    - title: What does 'Premises' mean?
      content: |
        'Premises' refers to the food shop you would like to obtain licences for.

    - title: Do I enter the name of my shop or the name of my registered business under 'Premises Name'?
      content: |
        You will need to enter the name of your shop under 'Premises Name'. This means the name you plan to display on your shopfront.

    - title: My business address does not have a level and/or unit number. What should I do?
      content: |
        If your business address does not have a level and/or unit number, please enter '00' under 'Level' and 'Unit Number' to proceed.

    - title: I accidentally added new premises, how can I delete the draft application/premises?
      content: |
        [Login to GoBusiness Guided Journey](https://foodservices.gobusiness.gov.sg/licences/foodservices?src=licences_faq){:target="_blank"}{:rel="noopener"}. Click on the premises you would like to delete. If the premises can be deleted, the “Remove” button will appear beside the “Premises Details” section title. Click on the “Remove” button to start the process of deletion.

        Premises can only be deleted if they contain draft application(s).

        Note: Deleted premises as well as their draft applications are not recoverable.

    - title: What does 'adjacent unit' mean?
      content: |
        Adjacent units are multiple units next to each other. This applies to businesses occupying multiple units. If your business occupies multiple levels without a connecting staircase within your premises, you will need to apply for individual licences for each level.

    - title: How do I find out the supporting documents I need for each licence?
      content: |
        Clicking on each licence in your Application Journey will show a list of supporting documents required. You can also refer to a full list of supporting documents on the 'Required Documents for your Licences' sidebar, located on the right side of your Application Journey.

    - title: Why are some supporting documents under 'Submit Now' and others are under 'Submit For Later'?
      content: |
        Documents under Submit Now will need to be uploaded once you submit your application, as they are required to start processing it.

        Documents under Submit Later will only be needed at a later stage, and can be submitted in future. However, you can choose to upload them together with your application.
        
    - title: How and when do I submit the supporting documents under 'Submit For Later'?
      content: |
        An officer from the respective government agency will be in touch to request for the documents.

    - title: How do I check on the status of my application?
      content: |
        All application status updates will be sent to the e-mail address provided in the application form.

        You can also check on each licence's current status on your Application Journey.

