accordion:
  - title: What is the Application for Change of Trade (HDB Commercial Properties) for?
    content: |
      The Application for Change of Trade is for HDB Commercial Tenants who wish to change their existing trade or include a new trade relating to sale of food & beverage in their rental HDB Commercial Properties.

  - title: Who can I contact for further details?
    content: |
      You may call HDB Commercial Hotline at 1800-8663073 or submit your enquiry via <a href="http://www.hdb.gov.sg/efeedback" target="blank">HDB Feedback Form</a>.

      You may also write in to:

      Properties & Land Group
      Housing & Development Board
      480 Lor 6 Toa Payoh
      Atrium 3rd Storey HDB Hub
      Singapore 310480

  - title: What supporting documents do I need to submit?
    content: |
      1. Proposed Layout Plan (mandatory for Restaurant and Family Restaurant)
      2. Details of Proposed operation (mandatory for Restaurant, Family Restaurant and Sale of Takeaway Food and Beverage)
      3. Trade Description

  - title: How much is the application fee?
    content: |
      A non-refundable administrative fee of $107 or $214 (inclusive of GST) shall be payable depending on the type of application.

  - title: What conditions do I need to fulfill?
    content: |
      Please read the <a href="https://www.hdb.gov.sg/cs/infoweb/terms-and-conditions/terms-and-conditions-for-application-for-change-of-trade-hdb-commercial-properties" target="blank">Terms and Conditions</a> for Application for Change of Trade (HDB Commercial Properties) and <a href="https://www.hdb.gov.sg/cs/infoweb/application-for-tenancy-change-of-hdb-commercial-properties/terms-and-conditions" target="blank">Terms and Conditions</a> for Application for Changes (HDB Commercial Properties).

  - title: How soon can my application be processed?
    content: |
      Processing takes 1 to 14 days upon HDB's verification of the information as declared in the online application and receipt of all supporting documents/information.

  - title: Do I need to submit this application?
    content: |
      You need to apply for Change of Trade if you are a HDB Commercial Tenant and you wish to change your existing trade or include a new trade relating to sale of food & beverage.

      For HDB Commercial Tenants who wish to change their existing trade or include a new trade together with other tenancy changes (e.g. change of business mode, change of partners, transfer or assignment of tenancy, renting out part of trading area or living quarters), they are to submit an online <a href="https://licence1.business.gov.sg/feportal/web/frontier/eAdvisor?agencyCode=HDB" target="blank">Application for Changes (HDB Commercial Properties)</a>.
